const mongoose = require('mongoose');

const orderSchema = mongoose.Schema({
	orderItems: [{ // array because order can contain multiple items in order
		type: mongoose.Schema.Types.ObjectId,
		ref: 'orderItem',
		required: true,
	}],
	shippingAddress1: {
		type: String,
		required: true,
	},
	shippingAddress2: {
		type: String,
	},
	city: {
		type: String,
		required: true,
	},
	zip: {
		type: String,
		required: true,
	},
	country: {
		type: String,
		required: true,
	},
	phone: {
		type: String,
		required: true,
	},
	status: {
		type: String,
		default: 'pending',
	},
	user: {
		type: mongoose.Schema.Types.ObjectId,
		ref: 'user',
	},
	dateOfOrder: {
		type: Date,
		default: Date.now, // generated by server automatically
	},
	totalPrice: {
		type: Number,
	},
})

// create a virtual "id" field (more frontend friendly)
orderSchema.virtual('id').get(function () {
	return this._id.toHexString();
})

// activate virtuals
orderSchema.set('toJSON', {
	virtuals: true,
})

//exports.Order = mongoose.model('Order', orderSchema); // the second way to export model outside it to be accessable by other files
module.exports = orderSchema;